version: "3"
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - 30444:4444
    environment:
      GRID_MAX_SESSION: 1
      GRID_BROWER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    container_name: selenium_hub


  tasty-food-seeker-chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium_hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1                       # 리모트 시스템에서 한번에 병렬로 실행할 수 있는 브라우저의 수
      NODE_MAX_INSTANCE: 1                      # 리모트 시스템에서 실행할 수 있는 동일 버전의 브라우저 인스턴스 수
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 39001:5900
    networks:
      - default
    container_name: tasty_food_seeker_chrome


  tasty-food-seeker-crawl:
    depends_on:
      - tasty-food-seeker-chrome
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LATEST_JAR=${LATEST_JAR}
        - YEAR=${YEAR}
        - MONTH=${MONTH}
    image: tasty_food_seeker_crawl:latest
    ports:
      - 30580:8080
    container_name: tasty_food_seeker_crawl


# using pre-existed user defined network
networks:
  default:
    external:
      name: tasty-food-seeker-network