server:
  port: 9111

spring:
  profiles:
    include:
      - override
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pasudo123/tasty-food-seeker-private
          timeout: 5
          skip-ssl-validation: true
          username: ${git.username}
          password: ${git.password}

---
spring:
  profiles: dev

---
spring:
  profiles: prod
