spring:
  profiles:
    active: dev
    include:

  freemarker:
    enabled: true
    template-loader-path: classpath:/templates
    suffix: .ftl
    content-type: text/html
    charset: UTF-8

  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://localhost:3306/tasty-food-seeker?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: refresh
---
spring:
  profiles: prod

  application:
    name: tastyfoodseeker

  datasource:
    url: jdbc:mysql://tasty_food_seeker_storage:3306/tasty-food-seeker?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    properties.hibernate.format_sql: false
    open-in-view: false

