spring:
  profiles:
    active: dev
    include:
      - secret

  freemarker:
    enabled: true
    template-loader-path: classpath:/templates
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
#    cache: false

  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://localhost:3306/tasty-food-seeker?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: false
    open-in-view: false

---
spring:
  profiles: dev
  # spring 실행 시 edit-configuration 에서 Running Application update policies 를 설정해준다.
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true


