spring:
  profiles:
    active: dev
    include:
      - secret
      - slack
  datasource:
    url: jdbc:mysql://localhost:3306/tasty-food-seeker?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: false
    open-in-view: false

web-driver.path: C:\develop\workspace\tasty-food-seeker\chromedriver.exe

---
spring:
  profiles: dev

---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://tasty_food_seeker_storage:3306/tasty-food-seeker?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    properties.hibernate.format_sql: false
    open-in-view: false

web-driver.path: http://selenium_hub:4444/wd/hub
