version: "3"
services:
  tasty-food-seeker-reverse-proxy:
    build:
      context: ./proxy  # directory :: ./proxy
      dockerfile: Dockerfile
    image: tasty_food_seeker_reverse_proxy:latest
    ports:
      - 31080:80
    container_name: tasty_food_seeker_reverse_proxy

  tasty-food-seeker-web:
    depends_on:
      - tasty-food-seeker-reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile
    image: tasty_food_seeker_web:latest
    ports:
      - 31580:8080
    container_name: tasty_food_seeker_web

networks:
  default:
    external:
      name: tasty-food-seeker-network