version: "3"
services:
  tasty-food-seeker-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tasty-food-seeker-web:latest
    ports:
      - 31580:8080
    container_name: tasty_food_seeker_web

networks:
  default:
    external:
      name: tasty-food-seeker-network