
name: Crawl CD with Gradle

on:
  push:
    branches:
      - release/crawl/**

jobs:
  build:
    name: build & scp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up timezone seoul
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: scp jar to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}         # using the git repository settings tab menu.
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # remote server source --> target 으로 jar 파일이 이동된다.
          source: ./tasty-food-seeker-crawl/build/libs/
          target: /volume1/docker/tasty-food-seeker/tasty-food-seeker-crawl/build/libs/
          rm: true
          strip_components: 4 # ., tasty-food-seeker-crawl, build, libs 는 target 으로 복사하지 않음

    deploy:
      needs: build
      name: deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: execute remote ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}                     # using the git repository settings tab menu.
            port: ${{ secrets.PORT }}
            username: ${{ secrets.REMOTE_SSH_USERNAME }}  # /etc/sudoers 부여
            password: ${{ secrets.REMOTE_SSH_PASSWORD }}
            script_stop: false
            scrips: |
              export PATH=/usr/local/bin:$PATH
              docker -v
              cd /volume1/docker/tasty-food-seeker/tasty-food-seeker-crawl
              sudo docker stop tasty_food_seeker_crawl
              sudo docker rm tasty_food_seeker_crawl
              sudo docker rmi tasty-food-seeker-crawl:latest
              sudo YEAR=${P_YEAR} MONTH=${P_MONTH} docker-compose up -d --build
