
name: Config-server CD with Gradle

on:
  push:
    branches:
      - release/configserver/**

jobs:
  build:
    name: build & scp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up timezone seoul
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Grant execute permission for gradlew
          run: chmod +x gradlew

      - name: scp jar to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ./tasty-food-seeker-config-server/build/libs/
          target: /volume1/docker/tasty-food-seeker/tasty-food-seeker-config-server/build/libs/
          rm: true
          strip_components: 4 # ., tasty-food-seeker-config-server, build, libs 는 target 으로 복사하지 않음

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          script_stop: true
          script: |
            export PATH=/usr/local/bin:$PATH
            docker -v
            cd /volume1/docker/tasty-food-seeker/tasty-food-seeker-config-server
            sudo docker stop tasty_food_seeker_configserver
            sudo docker rm tasty_food_seeker_configserver
            sudo docker rmi tasty-food-seeker-configserver:latest
            sudo docker-compose up --build -d